if(EXISTS "C:/projets/docker-googletest-cpp-project/build-windows/calculator_tests[1]_tests.cmake")
  include("C:/projets/docker-googletest-cpp-project/build-windows/calculator_tests[1]_tests.cmake")
else()
  add_test(calculator_tests_NOT_BUILT calculator_tests_NOT_BUILT)
endif()
