if(EXISTS "/workspace/build-asan/calculator_tests[1]_tests.cmake")
  include("/workspace/build-asan/calculator_tests[1]_tests.cmake")
else()
  add_test(calculator_tests_NOT_BUILT calculator_tests_NOT_BUILT)
endif()
